import type { StoreAnalysis } from "./analysis/schema"

/**
 * Code Fix Structure
 * Production-ready Shopify Liquid/CSS/HTML code generated by AI
 */
export interface CodeFix {
  /** The type of code being generated */
  type: "liquid" | "css" | "html" | "javascript"
  /** Target file in the Shopify theme (e.g., "sections/product-template.liquid") */
  targetFile: string
  /** Location in the file where the fix should be applied */
  targetLocation: string
  /** AI reasoning trace explaining WHY this fix addresses the issue */
  reasoningTrace: string
  /** The original code that exists (may be empty for new additions) */
  originalCode: string
  /** The optimized code to inject */
  optimizedCode: string
  /** Dependencies or prerequisites for this fix */
  dependencies?: string[]
  /** Estimated implementation effort */
  effort: "low" | "medium" | "high"
  /** Whether this fix requires theme editing permissions */
  requiresThemeAccess: boolean
}

export interface FrictionPoint {
  id: string
  title: string
  location: string
  impact: string
  affected: string
  fix: string
  /** AI-generated production-ready code fix */
  codeFix?: CodeFix
  /** Keywords associated with this friction point for attribution matching */
  keywords?: string[]
}

export interface PersonaResult {
  id: string
  name: string
  demographics: string
  verdict: "purchase" | "abandon"
  reasoning: string
  abandonPoint: string | null
}

export interface Recommendation {
  priority: number
  title: string
  impact: string
  effort: "low" | "medium" | "high"
  /** Estimated time to implement (e.g., "5-10 min", "15-30 min", "1-2 hours") */
  timeEstimate?: string
  description: string
  /** AI-generated production-ready code fix */
  codeFix?: CodeFix
}

export interface FunnelData {
  landed: number
  cart: number
  checkout: number
  purchased: number
}

export interface TestResult {
  id: string
  date: string
  url: string
  personaMix: string
  score: number
  previousScore?: number
  change?: number
  issuesFound: number
  status: "completed" | "running" | "failed"
  frictionPoints: {
    critical: FrictionPoint[]
    high: FrictionPoint[]
    medium: FrictionPoint[]
    working: string[]
  }
  personaResults: PersonaResult[]
  recommendations: Recommendation[]
  funnelData: FunnelData
  /** Optional detailed store analysis from structured schema */
  storeAnalysis?: StoreAnalysis
}

/**
 * Ghost Sandbox Types
 */
export interface SandboxTheme {
  id: number
  name: string
  role: "main" | "unpublished" | "demo"
  createdAt: string
  sourceThemeId: number
  status: "creating" | "ready" | "error"
}

export interface DeploymentResult {
  success: boolean
  themeId?: number
  themeName?: string
  previewUrl?: string
  error?: string
  errorCode?: "PERMISSION_DENIED" | "THEME_NOT_FOUND" | "API_ERROR" | "RATE_LIMITED"
  assetsUpdated?: string[]
}

export interface DeploymentRequest {
  shop: string
  accessToken: string
  fixes: Array<{
    frictionPointId: string
    codeFix: CodeFix
  }>
  createNewSandbox?: boolean
  existingSandboxId?: number
}

export interface AnalyzeRequest {
  url: string
  personaMix: string
}

export interface AnalyzeResponse {
  result: TestResult
}

// Re-export Shopify types for convenience
export type {
  AbandonedCheckout,
  AbandonedCheckoutStats,
  ShippingZone,
  ShippingRate,
  Country,
  ShippingShockAnalysis,
} from "./shopify/client"
